apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
arguments:
            STATE_VALUES_SET: HELM_REPO_ACCESS_TOKEN=$CF_API_KEY
data:
  myvalue: "Hello World"
  drink: {{ .Values.favoriteDrink }}
